---
platform: linux
inputs:
- name: kafka-repo
- name: kafka-prerelease-repo
- name: add-blobs
- name: version
outputs:
- name: release-tarball
- name: kafka-repo-release

run:
  path: kafka-repo/ci/tasks/create-final-release.sh

params:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
