---
name: kafka

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: kafka
  azs: [z1, z2, z3]
  instances: 1
  vm_resources:
    cpu: 2
    ram: 2048
    ephemeral_disk_size: 10240
  stemcell: default
  persistent_disk: 10240
  networks: [{name: default}]
  jobs:
  - name: zookeeper
    release: zookeeper
    properties: {}
  - name: kafka
    release: kafka
    properties:
      offsets:
        topic:
          replication:
            factor: 1
      transaction:
        state:
          log:
            replication:
              factor: 1
            min:
              isr: 1
  - name: kafka-manager
    release: kafka
    properties:
      username: admin
      password: ((kafka-manager-password))

variables:
- name: kafka-manager-password
  type: password

stemcells:
- alias: default
  os: ubuntu-xenial
  version: 456.latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: bpm
  sha1: 164b064b6aee268072739659ee5360a6f620d2c5
  stemcell:
    os: ubuntu-xenial
    version: "250.23"
  url: https://s3.amazonaws.com/kafka-boshrelease/compiled-releases/bpm/bpm-1.0.3-ubuntu-xenial-250.23-20190323-022540-20451776-20190323022545.tgz
  version: 1.0.3
- name: zookeeper
  sha1: 7f3fc333aa8b844f70e106328f4440bfbc9bb821
  stemcell:
    os: ubuntu-xenial
    version: "250.23"
  url: https://s3.amazonaws.com/kafka-boshrelease/compiled-releases/zookeeper/zookeeper-0.0.9-ubuntu-xenial-250.23-20190323-022303-721855212-20190323022311.tgz
  version: 0.0.9
- name: kafka
  sha1: a1531cd6410a4b9dda2014906cbee633b485a3c7
  stemcell:
    os: ubuntu-xenial
    version: "250.23"
  url: https://s3.amazonaws.com/kafka-boshrelease/compiled-releases/kafka/kafka-2.2.3-ubuntu-xenial-250.23-20190323-023747-677211024-20190323023753.tgz
  version: 2.2.3
