---
name: kafka

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: zookeeper
  azs: [z1, z2, z3]
  instances: 3
  jobs:
  - name: zookeeper
    release: zookeeper
    properties: {}
  - name: status
    release: zookeeper
    properties: {}
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  networks:
  - name: default
- name: kafka
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  networks: [{name: default}]
  jobs:
  - name: kafka
    release: kafka
    properties: {}
  - name: kafka-manager
    release: kafka
    properties: {}

variables: []

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: true

releases:
- name: bpm
  version: 0.2.0
  url: git+https://github.com/cloudfoundry-incubator/bpm-release
- name: zookeeper
  version: 0.0.7
  url: git+https://github.com/cppforlife/zookeeper-release
- name: kafka
  version: latest # TODO: update after first final release
  # url:            TODO: update after first final release
  # sha1:           TODO: update after first final release
