---
name: kafka

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: kafka
  azs: [z1, z2, z3]
  instances: 1
  vm_resources:
    cpu: 2
    ram: 2048
    ephemeral_disk_size: 10240
  stemcell: default
  persistent_disk: 10240
  networks: [{name: default}]
  jobs:
  - name: zookeeper
    release: zookeeper
    properties: {}
  - name: kafka
    release: kafka
    properties:
      offsets:
        topic:
          replication:
            factor: 1
      transaction:
        state:
          log:
            replication:
              factor: 1
            min:
              isr: 1
  - name: kafka-manager
    release: kafka
    properties:
      username: admin
      password: ((kafka-manager-password))

variables:
- name: kafka-manager-password
  type: password

stemcells:
- alias: default
  os: ubuntu-xenial
  version: 170.latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: bpm
  sha1: 53f5110cf27d99c9bfd2f4800a39a8cab3625153
  stemcell:
    os: ubuntu-xenial
    version: "170.30"
  url: https://s3.amazonaws.com/kafka-boshrelease/compiled-releases/bpm/bpm-1.0.3-ubuntu-xenial-170.25-20190212-175522-819086925-20190212175528.tgz
  version: 1.0.3
- name: zookeeper
  sha1: 14f34a5470d6c43c5663308dabe92167c16fc381
  stemcell:
    os: ubuntu-xenial
    version: "170.30"
  url: https://s3.amazonaws.com/kafka-boshrelease/compiled-releases/zookeeper/zookeeper-0.0.9-ubuntu-xenial-170.5-20181112-234055-046983265-20181112234105.tgz
  version: 0.0.9
- name: kafka
  sha1: f7585abe3605683b683fe0002d28aed3ae2a1c1c
  stemcell:
    os: ubuntu-xenial
    version: "170.30"
  url: https://github.com/cloudfoundry-community/kafka-boshrelease/releases/download/v2.2.3/kafka-2.2.3.tgz
  version: 2.2.3
